### ISSUE TITLE
Some client rects are redundant

### ISSUE THREAD

**Issue by chitgoks** [edg2s/rangefix#10]
I say redundant because the dimension of a few client rects are almost the same, with the only difference sometimes is lesser height by a few pixels or perhaps width.

Would be a nice feature if this gets cleaned up and only the rect with the larger area gets returned.

**Comment by edg2s** [comment]
I think returning nested rectangles would be correct according to the spec in some cases. I agree in most use cases you would want to cull those, but that might be beyond the scope of this library which is to fix more obvious errors.

**Comment by chitgoks** [comment]
true. not really a big issue but would be neat nonetheless. thanks for the feedback!
