### ISSUE TITLE
Some client rects appear twice

### ISSUE THREAD

**Issue by jahewson** [edg2s/rangefix#3]
The fixed version of getClientRects() returns two copies of client rects for RTL text. Here's a fork of your demo which shows the problem. If you select the first line line which includes the Arabic text, then view the highlights in the web inspector, you'll see that the client rect corresponding to the RTL span appears twice:

https://rawgit.com/jahewson/rangefix/master/demo.html

P.S. Good work with this fix, because Chrome doesn't seem to be progressing on this front.

**Comment by edg2s** [comment]
Thanks. I'm seeing them appear twice in native as well - so not as much a bug with the library as another bug with Chrome, but it would be good to fix it. Suggestions welcome.

**Comment by edg2s** [comment]
I don't think this has anything to do with RTL, I get the same result with just a short inline span.

**Comment by edg2s** [comment]
Behaviour matches native API, so marking as WONTFIX.
