### ISSUE TITLE
range.getBoundingClientRect() misbehaviour on multiline texts

### ISSUE THREAD

**Issue by fbuchinger** [edg2s/rangefix#5]
Hi,

I am experiencing a werid range.getBoundingClientRect() bug on https://www.theguardian.com/international. For my layout analyzer [layoutstats](https://github.com/fbuchinger/jquery.layoutstats), I want to calculate the area and the positions of all visible text nodes on the page. 

I am using range.getBoundingClientRect() for that purpose. If the analyzed textnode spans multiple lines, the reported left and right values of the ClientRect are way off the correct numbers (see code and screenshot), range.getClientRects() reports that there is just one client rect, however by [spec there should be multiple rects](https://drafts.csswg.org/cssom-view/#dom-element-getclientrects) (one for each line break)

```
s = document.querySelector('#spotlight > div >... (selector copied from chrome developer tools)...')
s.childNodes[0].textContent; //"America’s eviction epidemic"
r = document.createRange(); 
r.selectNode(s.childNodes[0]);
console.log(r.getBoundingClientRect());  
//ClientRect {top: 142.09375, right: 1295.75, bottom: 162.09375, left: 1081.5, width: 214.25…}
//expected {left: 438. right: 898, (other values ok)} - see screenshot
r.getClientRects() //1, should be 2 client rects according to spec
```
![image](https://cloud.githubusercontent.com/assets/287434/22864176/c1084886-f14c-11e6-9109-853f0327bc22.png)

Can rangefix correct this behaviour? If not, is this an intentional behaviour or a browser bug?

**Comment by edg2s** [comment]
Precisely which element did you select form the DOM tree? The leaf span that actually contains the text "America's eviction epidemic" returns 4 rectangles for me. If you select something higher up the tree you will probably get a single bounding box.

**Comment by fbuchinger** [comment]
i directly selected the text node "America's eviction epidemic" -here a console excerpt:
```
>sel = document.querySelector("#spotlight > div > div.fc-container--rolled-up-hide.fc-container__body.fc-show-more--hidden > div:nth-child(2) > ul > li:nth-child(2) > ul > li:nth-child(3) > div > div > a")
>var r= document.createRange(); r.selectNode(sel.childNodes[0]);r.getClientRects()
ClientRectList {0: ClientRect, length: 1}
```

**Comment by edg2s** [comment]
You directly clicked on the anchor `... > div > div > a` with the inspector which is display:block to make the whole banner clickable. As it is no longer display:inline it won't give you wrapped line boxes.

The text inside the anchor is invisible. the actual rendered text is a sibling node previous to the link (`.fc-item__header`), which is positioned underneath the clickable anchor.

**Comment by fbuchinger** [comment]
Thanks for pointing that out! Helped me to improve my visibility algorithm for text nodes. Now I not only check whether their parent node is visible, but also if they are visible within their parent node. In the guardian example the link text had so much offset that it simply got cropped off.
